---
- name: Reload sysctl
  become: true
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Restart k3s
  become: true
  ansible.builtin.systemd:
    name: "{{ k3s_service }}"
    state: restarted
    enabled: true

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
