---
- name: Update grub
  become: true
  ansible.builtin.command: update-grub
  changed_when: true

- name: Reload sysctl
  become: true
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Restart k3s
  become: true
  ansible.builtin.systemd:
    name: "{{ k3s_service }}"
    state: restarted

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
